-- MySQL Script generated by MySQL Workbench
-- lun. 16 mai 2022 16:04:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hero` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  `image` VARCHAR(100) NULL,
  `lifepoints` INT NOT NULL,
  `attack` INT UNSIGNED NOT NULL,
  `maxLifePoints` INT UNSIGNED NOT NULL,
  `maxAttack` INT UNSIGNED NOT NULL,
  `offensiveGear_id` INT UNSIGNED NOT NULL,
  `defensiveGear_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Board` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playerPosition` INT NULL,
  `cells_id` INT NULL,
  `Hero_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Board_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  CONSTRAINT `fk_Board_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `mydb`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cell` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cell` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` INT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enemy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Enemy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Enemy` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  `image` VARCHAR(100) NULL,
  `lifepoints` INT NOT NULL,
  `attack` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`board_has_cells`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`board_has_cells` ;

CREATE TABLE IF NOT EXISTS `mydb`.`board_has_cells` (
  `Board_id` INT NOT NULL,
  `Cell_id` INT NOT NULL,
  PRIMARY KEY (`Board_id`, `Cell_id`),
  INDEX `fk_board_has_cells_Board1_idx` (`Board_id` ASC) VISIBLE,
  INDEX `fk_board_has_cells_Cell1_idx` (`Cell_id` ASC) VISIBLE,
  CONSTRAINT `fk_board_has_cells_Board1`
    FOREIGN KEY (`Board_id`)
    REFERENCES `mydb`.`Board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_board_has_cells_Cell1`
    FOREIGN KEY (`Cell_id`)
    REFERENCES `mydb`.`Cell` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cell_has_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cell_has_event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cell_has_event` (
  `Cell_id` INT NOT NULL,
  `Event_id` INT NOT NULL,
  INDEX `fk_cell_has_event_Cell1_idx` (`Cell_id` ASC) VISIBLE,
  INDEX `fk_cell_has_event_Event1_idx` (`Event_id` ASC) VISIBLE,
  CONSTRAINT `fk_cell_has_event_Cell1`
    FOREIGN KEY (`Cell_id`)
    REFERENCES `mydb`.`Cell` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cell_has_event_Event1`
    FOREIGN KEY (`Event_id`)
    REFERENCES `mydb`.`Event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gear` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gear` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `stat` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hero_has_gear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hero_has_gear` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hero_has_gear` (
  `Gear_id` INT UNSIGNED NOT NULL,
  `Hero_id` INT UNSIGNED NOT NULL,
  INDEX `fk_hero_has_gear_Gear1_idx` (`Gear_id` ASC) VISIBLE,
  INDEX `fk_hero_has_gear_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  CONSTRAINT `fk_hero_has_gear_Gear1`
    FOREIGN KEY (`Gear_id`)
    REFERENCES `mydb`.`Gear` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hero_has_gear_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `mydb`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
